Add common info to state write
mobilutz/ioBroker.freeathome pull request #480
Opened 2022-07-26 23:15 UTC by mobilutz

2022-08-10 18:08 UTC, guerda commented on lib/freeathome.js
> +                write: false,
If I understand the API correctly, ioBroker expects a type property in this object. Can we add that here?

2022-08-10 18:08 UTC, guerda commented on lib/freeathome.js
> +                role: 'text'
Same here: Type could be missing

2022-08-10 18:18 UTC, guerda requested changes

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                        write: false
Same here: Type could be missing

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                            write: true
Same here: Type could be missing

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                write: false,
I think the type "string"

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                role: 'text'
I assume "string" is fitting for deviceId, too.

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                            write: true
This one is tough, I assume it could be of different types, depending on the device. I don't know what to specify here.

2022-08-10 18:18 UTC, guerda commented on lib/freeathome.js
> +                                write: false
This one is tough, I assume it could be of different types, depending on the device. I don't know what to specify here.

2022-08-12 06:37 UTC, guerda commented
@mobilutz : Thanks for the fixes!
I actually removed my usual instance and created a new one with the adapter from this branch. This worked fine of course :)

The documentation is not really clear how you specify the type when it's basically a mixed type. I understand that the combination of common.type and other attributes could suffice for ioBroker. 

I'll try out the new changes soon and report back.

2022-08-13 12:08 UTC, guerda commented
I installed the latest version of this branch and unfortunately, this crashes completely and does not come up anymore:

```
freeathome.0 | 2022-08-13 14:00:07.059 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
freeathome.0 | 2022-08-13 14:00:07.058 | info | terminating
freeathome.0 | 2022-08-13 14:00:07.051 | error | Cannot convert undefined or null to object
freeathome.0 | 2022-08-13 14:00:07.050 | error | TypeError:  Cannot convert undefined or null to object    at Function.keys  (<anonymous>)    at Freeathome.registerAllDevices  (/opt/iobroker/node_modules/iobroker.freeathome/main.js:44:24)    at  processTicksAndRejections (internal/process/task_queues.js:95:5)
freeathome.0 | 2022-08-13 14:00:07.050 | error | unhandled promise rejection: Cannot convert undefined or null to object
freeathome.0 | 2022-08-13 14:00:07.049 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
freeathome.0 | 2022-08-13 14:00:06.980 | info | Starting free@home API
```

I currently do not see any property or object which is accessed in comparison to before.
Can it be that with the newest commits it initially goes further and then a device fails which was previously untouched.
Unfortunately, I don't know which device that might be...

Sorry for being so unhelpful.

2022-08-24 20:16 UTC, mobilutz commented
@guerda I removed some code.
Could you try again.

Looking at the error code you posted, I am certain that it is not related to this change!

2022-08-29 08:46 UTC, guerda commented
Thanks, @mobilutz ! 
It still immediately crashes, now with different errors.

```
2022-08-29 10:44:11.247 - info: freeathome.0 (19300) starting. Version 0.0.11 (non-npm: mobilutz/ioBroker.freeathome#refs/heads/ll-add-common-info) in /opt/iobroker/node_modules/iobroker.freeathome, node: v14.19.2, js-controller: 4.0.23
2022-08-29 10:44:11.295 - info: freeathome.0 (19300) Starting free@home API
2022-08-29 10:44:13.145 - info: freeathome.0 (19300) undefined is not a valid state value for id "freeathome.0.undefined.deviceId"
2022-08-29 10:44:13.147 - info: freeathome.0 (19300) undefined is not a valid state value for id "freeathome.0.undefined.deviceId"
2022-08-29 10:44:13.147 - info: freeathome.0 (19300) undefined is not a valid state value for id "freeathome.0.undefined.deviceId"
2022-08-29 10:44:13.150 - error: freeathome.0 (19300) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-29 10:44:13.151 - error: freeathome.0 (19300) unhandled promise rejection: Cannot read property 'serialNumber' of undefined
2022-08-29 10:44:13.152 - error: freeathome.0 (19300) TypeError: Cannot read property 'serialNumber' of undefined
at FreeAtHomeApi.addDeviceToioBroker (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:71:37)
at FreeAtHomeApi.broadcastMessage (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:65:22)
at Client. (/opt/iobroker/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:91:29)
at Client.emit (events.js:412:35)
at /opt/iobroker/node_modules/@xmpp/middleware/index.js:19:28
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-08-29 10:44:13.152 - error: freeathome.0 (19300) Cannot read property 'serialNumber' of undefined
2022-08-29 10:44:13.154 - error: freeathome.0 (19300) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-29 10:44:13.154 - error: freeathome.0 (19300) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-08-29 10:44:13.157 - error: freeathome.0 (19300) Error: The id is empty! Please provide a valid id.
at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
at Freeathome.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3181:23)
at FreeAtHomeApi.addDeviceToioBroker (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:72:22)
at FreeAtHomeApi.broadcastMessage (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:65:22)
at Client. (/opt/iobroker/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:91:29)
at Client.emit (events.js:412:35)
at /opt/iobroker/node_modules/@xmpp/middleware/index.js:19:28
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-08-29 10:44:13.158 - error: freeathome.0 (19300) The id is empty! Please provide a valid id.
2022-08-29 10:44:13.158 - error: freeathome.0 (19300) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-29 10:44:13.159 - error: freeathome.0 (19300) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-08-29 10:44:13.160 - error: freeathome.0 (19300) Error: The id is empty! Please provide a valid id.
at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
at Freeathome.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3181:23)
at FreeAtHomeApi.addDeviceToioBroker (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:72:22)
at FreeAtHomeApi.broadcastMessage (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:65:22)
at Client. (/opt/iobroker/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:91:29)
at Client.emit (events.js:412:35)
at /opt/iobroker/node_modules/@xmpp/middleware/index.js:19:28
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-08-29 10:44:13.160 - error: freeathome.0 (19300) The id is empty! Please provide a valid id.
2022-08-29 10:44:13.161 - error: freeathome.0 (19300) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-29 10:44:13.161 - error: freeathome.0 (19300) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-08-29 10:44:13.162 - error: freeathome.0 (19300) Error: The id is empty! Please provide a valid id.
at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
at Freeathome.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3181:23)
at FreeAtHomeApi.addDeviceToioBroker (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:72:22)
at FreeAtHomeApi.broadcastMessage (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:65:22)
at Client. (/opt/iobroker/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:91:29)
at Client.emit (events.js:412:35)
at /opt/iobroker/node_modules/@xmpp/middleware/index.js:19:28
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-08-29 10:44:13.162 - error: freeathome.0 (19300) The id is empty! Please provide a valid id.
2022-08-29 10:44:13.173 - info: freeathome.0 (19300) terminating
2022-08-29 10:44:13.174 - warn: freeathome.0 (19300) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-08-29 10:44:13.738 - error: host.0bec687dd865 instance system.adapter.freeathome.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-29 10:44:23.728 - info: daikin.1 (17604) Daikin Device initialized with Error :Error occured: Error while communicating with Daikin device: EHOSTUNREACH
2022-08-29 10:44:23.729 - info: daikin.1 (17604) Retry init in 60 seconds

```


During the installation, the following warnings came up:
```
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

npm WARN deprecated @xmpp/resolve@0.7.4: Potential security vulnerability fixed in 0.13.1 - see https://github.com/xmppjs/xmpp.js/pull/936

npm WARN deprecated @xmpp/tls@0.7.4: Critical security bug fixed in v0.12.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
```
Maybe this is less important and can be tackled later.

2022-11-26 20:11 UTC, mobilutz commented
@guerda I finally got around to creating a dedicated testing instance inside docker to test out my changes.

I added this branches adapter, and did not see any errors.

I will merge this, and update the adapter.

2022-11-26 20:12 UTC, guerda commented
Sounds good, I assume it is a config error on my installation.

2022-11-26 20:15 UTC, merged